[programs.devnet]
myepicproject = "8BgZp17gyuSK1DZ24ULkwsRnri6kJrQyDjq4ygCmEVqB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/alecchen/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
test_prev = "mocha -t 1000000 tests/"
